##################################################
# Main configuration

title:           'Island Labs'
locale:          'en_US'
production:      true
sidebar_page:    'Sidebar'
base_path:      './'

cache_store:
  type:   file
  file:
    root: './wiki/cache'

math_renderer: mathjax
blahtex_directory: './wiki/blahtex'

theme: atlantis

##################################################
# Authentication backend configuration

authentication:
  enable_signup: true
  service:       yamlfile

  yamlfile:
    store:       './wiki/users.yml'

 # portal:
 #   url:         'http://portal.heroku.com/'

  # Stack backend which accesses multiple backends in the following order.
  stack:
    - yamlfile
#    - portal

# Where to store authentication tokens for persistent login.
# See the store types of cache_store.
# Uncomment this!
tokens_store:
  type: pstore
  pstore:
    file: './wiki/tokens.pstore'

##################################################
# Mime detection order
# Possible values are extension, content/magic and a specific mime type
# You can configure the wiki default mime type here
# and select the default wiki text this way.

mime:
  - extension
  - content
  # Use creole as last resort.
  # You can configure the wiki default mime type here!
  # Use text/x-creole for Creole Wikitext, text/x-markdown for Markdown,
  # text/x-maruku for Markdown/Maruku, text/x-textile for Textile, text/x-orgmode for Emacs Org Mode
  - text/x-creole

mime_suggestions:
  - text/x-creole
  - text/x-markdown
  - text/x-markdown.maruku
  - text/x-markdown.kramdown
  - text/x-textile
  - text/x-orgmode

##################################################
# List of disabled plugins by name.
# You can disable whole plugin directories.

disabled_plugins:
  - security/readonly_wiki
  - security/private_wiki
  - editor/antispam

##################################################
# Rack middleware configurations

rack:
  # Secret key used to verify session integrity. Use a random string here!
  session_secret: '7d57af9e-0abe-4eb2-bee5-c2135fd26d83'
  # Use the deflater to compress data (Rack::Deflater)
  deflater:      true
  # Specify a list of blacklisted ips which cannot post data
  blacklist:     []

##################################################
# Logging configuration

log:
  level: INFO
  file: './wiki/log'

##################################################
# Antispam configuration.
# Specify recaptcha public/private key

antispam:
  recaptcha:
    public:      6LdIxsISAAAAAIrALbZPrZgsJ1NLcYz5UH1gZ4SM
    private:     6LdIxsISAAAAAJk5ovBondFSNjcZ8N7DYbaujzhR

##################################################
# Repository configuration

repository:
  # Specify type of repository
  type:          git

  # Configuration git repository type. Uncomment this!
  # Path is to a bare (!) git repository.
  git:
    path:        './repository'
    bare:        true
